{
java.specification.version=23,
 sun.cpu.isalist=amd64, 
sun.jnu.encoding=Cp1252,
 java.class.path=.,
 java.vm.vendor=Oracle Corporation,
 sun.arch.data.model=64,
 user.variant=,
 java.vendor.url=https://java.oracle.com/,
 java.vm.specification.version=23,
 os.name=Windows 11,
 sun.java.launcher=SUN_STANDARD,
 user.country=US,
 sun.boot.library.path=C:\Program Files\Java\jdk-23\bin, sun.java.command=jdk.jshell.execution.RemoteExecutionControl 52571, jdk.debug=release,
 sun.cpu.endian=little, 
user.home=C:\Users\DELL, 
user.language=en,
 java.specification.vendor=Oracle Corporation,
 java.version.date=2024-09-17,
 java.home=C:\Program Files\Java\jdk-23, 
file.separator=\,
 j ... Python313\Scripts\;
C:\Users\DELL\AppData\Local\Programs\Python\Python313\;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;;.,
 jdk.console=jdk.jshell, 
java.vm.info=mixed mode,
 sharing,
 stderr.encoding=Cp1252,
 java.vendor=Oracle Corporation,
 java.vm.version=23+37-2369, 
sun.io.unicode.encoding=UnicodeLittle,
 java.class.version=67.0}